version: '2.2'
services:
  mongodb1:
    image: mongo:latest
    volumes:
      - data-01:/data/db
      - config-01:/data/configdb
      - ./log/mongodb:/log 
    ports:
      - 27017:27017
    command:
      - '--logpath'
      - './log/mongodb.log'
      - '--profile=1'
      - '--slowms=1'
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    
  mongodb2:
    image: mongo:latest
    ports:
      - 27018:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    
  mongodb3:
    image: mongo:latest
    ports:
      - 27019:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    
  mongoclient:
    image: mongo
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    volumes:
      - ./initiate_replica.sh:/deployment_scripts/initiate_replica.sh
    entrypoint:
      - /deployment_scripts/initiate_replica.sh

  nginx:
    image: nginx:latest
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
    ports:
      - '8080:80'
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'

  node:
    image: node:10.14
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: 'npm start'

  es-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es-01
    environment:
      - node.name=es-01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib-01:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kib-01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es-01:9200
      ELASTICSEARCH_HOSTS: http://es-01:9200
    networks:
      - elastic

volumes:
  data-01:
    driver: local
  config-01:

networks:
  elastic:
    driver: bridge
